### ISSUE TITLE
Ghostscript command to  FLATTEN ANNOTATIONS but keep HYPERLINKS alive

### ISSUE THREAD

**Issue by Geo-Van** [ArtifexSoftware/Ghostscript.NET#113]
Please let me ask regarding the wonderful feature **_-dPreserveAnnots_** :

Applying {   **-dPreserveAnnots=false**    } on a PDF file,
it flattens ANNOTATIONS, but also it flattens all the HYPERLINKS contained in the initial pdf file.
Is there a way to flatten annotations but keep HYPERLINKS alive, please?

**Comment by jhabjan** [comment]
You can use -dPreserveAnnotTypes

Take a look under the PreserveAnnots switch here: https://ghostscript.readthedocs.io/en/latest/VectorDevices.html#pdf-file-output-pdfwrite

If you preserve Link annotations then hyperlinks should continue to work.

**Comment by Geo-Van** [comment]
Thank you very much!
This gives me the correct explanation. Thank you!
Please note that before Ghostscript version 9.27 (included), the following Ghostscript command assumes separate "thing" annotations AND Hyperlinks :
**_-dPreserveAnnots=true_** 
So, when applied to a pdf file, it gives ---->  Annotations Flatten & Hyperlinks not Flatten

But as your answer, Ghostscript after version 9.27, "CHANGE POLICY" and correctly assumes annotations AND hyperlinks "same thing".

But is there an extra COMMAND to can use in order to **_"separate"_** annotations from hyperlinks as versions 9.27 and before do?

**Comment by jhabjan** [comment]
You can use -dPreserveAnnotTypes

Take a look under the PreserveAnnots switch here: https://ghostscript.readthedocs.io/en/latest/VectorDevices.html#pdf-file-output-pdfwrite

If you preserve Link annotations then hyperlinks should continue to work.

**Comment by Geo-Van** [comment]
Thank you very much! Very interesting info.
Please help me to do it work with an example -  Lets say i have the following command:
**gs.exe -o output.pdf -dPreserveAnnots=false -sDEVICE=pdfwrite  input.pdf**

According to your answer, now, i must add the follow to the command line in order to flatten annotations but keep hyperlinks alive:   **_-c "/PreserveAnnotTypes [/Link] def" -f_**

I try to "marry" the above two in the correct command format, but with no success:
**gs.exe -o output.pdf -dPreserveAnnots=false -c "/PreserveAnnotTypes [/Link] def" -f -sDEVICE=pdfwrite  input.pdf**

Can you please show us how to do it correct, please?

**Comment by jhabjan** [comment]
It should look something like this:

`gs -dNOPAUSE -dQUIET -dBATCH -sDEVICE=pdfwrite -sOutputFile=output.pdf -c "/PreserveAnnotTypes [/Link] def" -f basic_link_1.pdf
`

there should not be any more switches after -f, only input filenames

**Comment by Geo-Van** [comment]
Thanks for your reply, 
I try:
gs -dNOPAUSE -dQUIET -dBATCH -sDEVICE=pdfwrite -sOutputFile=output.pdf -c "/PreserveAnnotTypes [/Link] def" -f basic_link_1.pdf 
BUT, please note that this is NOT working, unfortunately.....  it flatten NOTHING, all annotations are NOT flatten, and hyperlinks are also NOT flatten.   
Where is the error regarding the above command SYNTAX, please?

**Comment by jhabjan** [comment]
I've tried this and it doesn't work for me either. 

`gs -dNOPAUSE -dQUIET -dBATCH -sDEVICE=pdfwrite -sOutputFile=output.pdf -dPreserveAnnots=false -c "/PreserveAnnotTypes [/Link] def" -f basic-link-1.pdf`

You can report core Ghostscript bugs here: [bugs.ghostscript.com](bugs.ghostscript.com)

**Comment by Geo-Van** [comment]
Thank you, 
Report is done at:

https://github.com/ArtifexSoftware/Ghostscript.NET/issues/116

**Comment by Geo-Van** [comment]
Hello,
The latest version 10.02 works:
gs -sDEVICE=pdfwrite -o output.pdf -c "/PreserveAnnotTypes [/Link] def" -f input.pdf

Thank you!
