### ISSUE TITLE
Ghostscript - completely REMOVE METADATA from pdf files

### ISSUE THREAD

**Issue by Geo-Van** [ArtifexSoftware/Ghostscript.NET#114]
Hello,
Please let me ask regarding Ghostscript - completely REMOVE METADATA from pdf files.

(1) With the help of the **_pdfmark.txt_** (txt file containing the below info and saved in same directory as the Ghostscript executable (gs.exe), we can use the following command to completely remove any metadata from a pdf file:
Command:   **_gs.exe -o output.pdf  -sDEVICE=pdfwrite input.pdf  pdfmark.txt_**

Note the pdfmark.txt file content:

 **_[ /Title ()
  /Author ()
  /Subject ()
  /Creator ()
  /ModDate ()
  /Producer ()
  /Keywords ()
  /CreationDate ()
/DOCINFO pdfmark_**

Please let me ask:
                            (a) The above method of removing metadata is completely permanent - irreversible? Or is there a way to reverse 
                                  (get back the original metadata), please?
                            (b) The above method used to work 100% in previous Ghostscript releases including the PRODUCER name.
                                  But unfortunately in latest versions, the PRODUCER name can not be changed - ALWAYS writes GHOSTSCRIPT as 
                                  producer name. It seems that IGNORES the command **_/Producer ()_** from the **_pdfmark.txt_**
                                  Is there anything we can do in order to change the PRODUCER name, please?

(2) XMP metadata:
How can we also completely remove any XMP metadata from a pdf file, please?
I use the following SINGLE **_pdfmark.txt_** , but it seems that creates a "new" XMP metadata:

**[ /Title ()
  /Author ()
  /Subject ()
  /Creator ()
  /ModDate ()
  /Producer ()
  /Keywords ()
  /CreationDate ()
/DOCINFO pdfmark**

**[ /XML ()
/Ext_Metadata pdfmark**

Please let me ask:
                           (a) Is the above **_pdfmark.txt_** correct, please?
                           (b) If yes, then why the created new pdf file it seems that creates a "new" XMP metadata?

We are looking forward for your reply.
Many thanks!

**Comment by jhabjan** [comment]
Try to use -dOmitXMP=true

**Comment by Geo-Van** [comment]
Thanks for your reply, but please note that:
**_-dOmitXMP=true_**
according to documentation, it is required when producing PDF/A output . 

But, please note that my question refers to NOT PDF/A output . (sorry i did not mention it before).

So, any more ideas, please?

*By the way is the syntax of pdfmark.txt correct? (INCLUDING ZERO XMP metadata):


**[ /Title ()
/Author ()
/Subject ()
/Creator ()
/ModDate ()
/Producer ()
/Keywords ()
/CreationDate ()
/DOCINFO pdfmark**

**[ /XML ()
/Ext_Metadata pdfmark**

**Comment by jhabjan** [comment]
You cannot remove the XMP metadata from a conforming PDF/A file, it's a requirement of the specification. Other PDF types may be similar, and Ghostscript will, of course, always insert XMP if required by the specification.

You can't touch the Producer key/value pair in the Info dictionary, Ghostscript always write the Producer and it's always set to "Ghostscript". This is to prevent people changing it and passing off Ghostscript produced PDF files as their own work.

**NOTE:**
This is Ghostscript.NET repository, which serves as a .NET wrapper for the core Ghostscript library. If you have questions about the core Ghostscript functionality, I suggest seeking assistance in the [#ghostscript](https://discord.gg/H9GXKwyPvY) Discord channel.

**Comment by Geo-Van** [comment]
Thank you very much for your reply.

So, if i get it correct:

If i use Ghostscript to REMOVE ALL metadata from a pdf file by using the pdfmark.txt (as described at the end of this comment), 
**_XMP metadata will be created inside the new pdf file, but it will be an "EMPTY" XMP metadata_** _("empty" - means that contains no metadata info - it contains  only the metadata XMP **structure** which is the same for every pdf file)_.
**So actually the command:    gs.exe -o output.pdf -sDEVICE=pdfwrite input.pdf pdfmark.txt
will REMOVE ALL metadata including the XMP metadata.**
Do i understand it correct, please?


**NOTE:**
The following pdfmark.txt , will remove all metadata but it will create a "new"  "EMPTY" XMP metadata:
(note that the **[ /XML ()    /Ext_Metadata pdfmark**       ---> is NOT needed.

**_[ /Title ()
/Author ()
/Subject ()
/Creator ()
/ModDate ()
/Producer ()
/Keywords ()
/CreationDate ()
/DOCINFO pdfmark_**

**Comment by Geo-Van** [comment]
Please see
https://github.com/ArtifexSoftware/Ghostscript.NET/issues/117
