### ISSUE TITLE
-dPreserveAnnotTypes  NOT Working

### ISSUE THREAD

**Issue by Geo-Van** [ArtifexSoftware/Ghostscript.NET#116]
-dPreserveAnnotTypes NOT Working

Taking a look under the PreserveAnnots switch here: 
https://ghostscript.readthedocs.io/en/latest/VectorDevices.html#pdf-file-output-pdfwrite

Trying to apply the -dPreserveAnnotTypes  is NOT working, for example lets try the following to preserve HYPERLINKS:
Example:
**gs -dNOPAUSE -dQUIET -dBATCH -sDEVICE=pdfwrite -sOutputFile=output.pdf -c "/PreserveAnnotTypes [/Link] def" -f basic_link_1.pdf**

BUT, please note that this is NOT working, unfortunately..... it flatten NOTHING, all annotations are NOT flatten, and hyperlinks are also NOT flatten.

Also we try the following, and it doesn't work  either:
**gs -dNOPAUSE -dQUIET -dBATCH -sDEVICE=pdfwrite -sOutputFile=output.pdf -dPreserveAnnots=false -c "/PreserveAnnotTypes [/Link] def" -f basic-link-1.pdf**

Please see the relevant issue at:
https://github.com/ArtifexSoftware/Ghostscript.NET/issues/113

Can you please examine where is the error regarding -dPreserveAnnotTypes switch ?

**Comment by jhabjan** [comment]
Hi Geo-Van, like I said, please report this to the core Ghostscript website: https://bugs.ghostscript.com/

This here is Ghostscript.NET wrapper repository.

**Comment by Geo-Van** [comment]
Thank you, please see:

https://bugs.ghostscript.com/show_bug.cgi?id=707198

**Comment by Geo-Van** [comment]
Hello,
The latest version 10.02 works:
gs -sDEVICE=pdfwrite -o output.pdf -c "/PreserveAnnotTypes [/Link] def" -f input.pdf

Thank you!
